### ISSUE TITLE
Webhook error

### ISSUE THREAD

**Issue by impruthvi** [impruthvi/my-ai#20]
Webhook Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe?

```

export async function POST(req: Request) {
  const body = await req.text()
  const signature = headers().get("Stripe-Signature") as string

  let event: Stripe.Event

  try {
    event = stripe.webhooks.constructEvent(
      body,
      signature,
      process.env.STRIPE_WEBHOOK_SECRET!
    )
  } catch (error: any) {
    console.log(`Webhook Error: ${error.message}`);
    
    return new NextResponse(`Webhook Error: ${error.message}`, { status: 400 })
  }
}

```

**Comment by Divasraj1** [comment]
were you able to resolve this issue?

**Comment by impruthvi** [comment]
> were you able to resolve this issue?

Not resolved yet 😞

**Comment by impruthvi** [comment]
> were you able to resolve this issue?

Uh-oh! 🙈 My bad! 🤦‍♂️ Sent the webhook ID instead of the secret handshake. 🤐 #TypoTroubles
